---
- name: jalusw
  hosts: localhost
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
    - name: Install curl
      apt:
        name: curl
        state: present
    - name: Install essential utilities
      apt:
        name:
          - stow
          - git
          - zsh
          - tmux
          - vim
          - fzf
          - ripgrep
          - fd-find
          - kitty
          - build-essential
          - i3
          - i3status
          - nodejs
          - npm
          - software-properties-common
        state: present
        update_cache: yes
    - name: stow
      ansible.builtin.shell: stow .
    - name: install oh my zsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - name: add neovim apt repository
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/unstable
    - name: install neovim
      apt:
        name: neovim
    - name: install latest nodejs
      ansible.builtin.shell: npm i -g n && n lts
