font_size        14
font_family      RecMonoCasual Nerd Font Mono
bold_font        RecMonoCasual Nerd Font Mono
italic_font      RecMonoCasual Nerd Font Mono
bold_italic_font RecMonoCasual Nerd Font Mono
