# reference: https://sw.kovidgoyal.net/kitty/conf/

# Font
font_size 12
font_ltr yes
font_family Fira Code Nerd Font

# Window
window_padding_width 8
background_opacity 0.9

# Monochromatic
background #0A0A12
foreground #E8E6F0
cursor #888888
cursor_text_color #0A0A12
selection_background #CCCCCC
selection_foreground #0A0A12

color0 #0A0A12
color1 #555555
color2 #E0E0E0
color3 #CCCCCC
color4 #CCCCCC
color5 #888888
color6 #E0E0E0
color7 #E8E6F0
color8 #1C1C28
color9 #666666
color10 #DDDDDD
color11 #AAAAAA
color12 #AAAAAA
color13 #999999
color14 #EEEEEE
color15 #EBEBF2

# Keymaps
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+k scroll_up
map ctrl+j scroll_down
