vim.g.colors_name = "monochrome"
vim.o.background = "dark"

local C = {
  bg0 = "#0A0A12", bg1 = "#14141F", bg2 = "#1E1E2E",
  fg0 = "#E8E6F0", fg1 = "#9C9AB0", border = "#2A2A3D",
  primary = "#CCCCCC", light = "#E0E0E0", lighter = "#F0F0F0",
  dark = "#888888", darker = "#555555", muted = "#333333",
}

local hl = function(group, val)
  vim.api.nvim_set_hl(0, group, val)
end

hl("Normal", { fg = C.fg0, bg = C.bg0 })
hl("NormalNC", { fg = C.fg0, bg = C.bg0 })
hl("NormalFloat", { fg = C.fg0, bg = C.bg1 })
hl("EndOfBuffer", { fg = C.border })
hl("Cursor", { fg = C.bg0, bg = C.dark })
hl("lCursor", { fg = C.bg0, bg = C.dark })
hl("CursorIM", { fg = C.bg0, bg = C.dark })
hl("TermCursor", { fg = C.bg0, bg = C.dark })
hl("TermCursorNC", { fg = C.fg0, bg = C.bg2 })
hl("CursorLine", { bg = C.bg2 })
hl("CursorColumn", { bg = C.bg1 })
hl("CursorLineNr", { fg = C.primary, bold = true })
hl("LineNr", { fg = C.fg1 })
hl("CursorLineFold", { fg = C.fg1, bg = C.bg2 })
hl("CursorLineSign", { fg = C.fg1, bg = C.bg2 })
hl("FoldColumn", { fg = C.border, bg = C.bg0 })
hl("Folded", { fg = C.fg1, bg = C.bg1 })
hl("SignColumn", { fg = C.fg1, bg = C.bg0 })
hl("ColorColumn", { bg = C.bg2 })
hl("Conceal", { fg = C.fg1 })
hl("Visual", { fg = C.fg0, bg = C.border })
hl("VisualNOS", { fg = C.fg0, bg = C.border })
hl("Search", { fg = C.bg0, bg = C.lighter })
hl("IncSearch", { fg = C.bg0, bg = C.dark })
hl("CurSearch", { fg = C.bg0, bg = C.primary })
hl("MatchParen", { fg = C.primary, bg = C.bg2, bold = true })
hl("NonText", { fg = C.border })
hl("SpecialKey", { fg = C.border })
hl("Whitespace", { fg = C.border })
hl("Title", { fg = C.primary, bold = true })
hl("Directory", { fg = C.primary })
hl("Underlined", { fg = C.primary, underline = true })
hl("Ignore", { fg = C.bg2 })
hl("Error", { fg = C.darker, bg = C.bg1 })
hl("ErrorMsg", { fg = C.darker, bg = C.bg1 })
hl("WarningMsg", { fg = C.lighter })
hl("MoreMsg", { fg = C.light })
hl("Question", { fg = C.light })
hl("ModeMsg", { fg = C.fg1 })
hl("MsgArea", { fg = C.fg0, bg = C.bg0 })
hl("MsgSeparator", { fg = C.border })
hl("Todo", { fg = C.lighter, bg = C.bg1 })
hl("QuickFixLine", { fg = C.primary, bg = C.bg2 })
hl("qfLineNr", { fg = C.lighter })

hl("StatusLine", { fg = C.fg0, bg = C.bg2 })
hl("StatusLineNC", { fg = C.fg1, bg = C.bg1 })
hl("StatusLineTerm", { fg = C.fg0, bg = C.bg2 })
hl("StatusLineTermNC", { fg = C.fg1, bg = C.bg1 })
hl("TabLine", { fg = C.fg1, bg = C.bg1 })
hl("TabLineSel", { fg = C.bg0, bg = C.primary, bold = true })
hl("TabLineFill", { fg = C.border, bg = C.bg0 })
hl("WinBar", { fg = C.fg1, bg = C.bg0 })
hl("WinBarNC", { fg = C.fg1, bg = C.bg0 })
hl("WinSeparator", { fg = C.border, bg = C.bg0 })
hl("VerticalSplit", { fg = C.border, bg = C.bg0 })
hl("FloatBorder", { fg = C.dark, bg = C.bg1 })
hl("FloatTitle", { fg = C.primary, bg = C.bg1 })
hl("FloatFooter", { fg = C.fg1, bg = C.bg1 })
hl("Pmenu", { fg = C.fg0, bg = C.bg1 })
hl("PmenuSel", { fg = C.bg0, bg = C.primary })
hl("PmenuSbar", { bg = C.bg2 })
hl("PmenuThumb", { bg = C.border })
hl("WildMenu", { fg = C.bg0, bg = C.dark })
hl("ScrollbarThumb", { bg = C.border })
hl("ScrollbarTrack", { bg = C.bg0 })
hl("SpellBad", { undercurl = true, sp = C.darker })
hl("SpellCap", { undercurl = true, sp = C.lighter })
hl("SpellLocal", { undercurl = true, sp = C.primary })
hl("SpellRare", { undercurl = true, sp = C.muted })

hl("DiffAdd", { fg = C.light, bg = C.bg1 })
hl("DiffChange", { fg = C.lighter, bg = C.bg1 })
hl("DiffDelete", { fg = C.darker, bg = C.bg1 })
hl("DiffText", { fg = C.primary, bg = C.bg2 })

hl("Comment", { fg = C.fg1, italic = true })
hl("Constant", { fg = C.lighter })
hl("String", { fg = C.light })
hl("Character", { fg = C.lighter })
hl("Number", { fg = C.lighter })
hl("Float", { fg = C.lighter })
hl("Boolean", { fg = C.muted })
hl("Identifier", { fg = C.fg0 })
hl("Function", { fg = C.primary })
hl("Statement", { fg = C.dark })
hl("Conditional", { fg = C.dark })
hl("Repeat", { fg = C.dark })
hl("Label", { fg = C.muted })
hl("Operator", { fg = C.primary })
hl("Keyword", { fg = C.dark })
hl("Exception", { fg = C.darker })
hl("PreProc", { fg = C.muted })
hl("Include", { fg = C.muted })
hl("Define", { fg = C.muted })
hl("Macro", { fg = C.muted })
hl("PreCondit", { fg = C.muted })
hl("Type", { fg = C.muted })
hl("StorageClass", { fg = C.dark })
hl("Structure", { fg = C.muted })
hl("Typedef", { fg = C.muted })
hl("Special", { fg = C.lighter })
hl("SpecialChar", { fg = C.lighter })
hl("SpecialComment", { fg = C.fg1, italic = true })
hl("Tag", { fg = C.lighter })
hl("Delimiter", { fg = C.fg1 })
hl("Debug", { fg = C.lighter })

hl("@comment", { fg = C.fg1, italic = true })
hl("@comment.error", { fg = C.darker, italic = true })
hl("@comment.warning", { fg = C.lighter, italic = true })
hl("@comment.todo", { fg = C.lighter, bg = C.bg1 })
hl("@comment.note", { fg = C.primary, italic = true })
hl("@error", { fg = C.darker })
hl("@punctuation.delimiter", { fg = C.fg1 })
hl("@punctuation.bracket", { fg = C.fg1 })
hl("@punctuation.special", { fg = C.lighter })
hl("@string", { fg = C.light })
hl("@string.documentation", { fg = C.light, italic = true })
hl("@string.escape", { fg = C.lighter })
hl("@string.regex", { fg = C.lighter })
hl("@string.special", { fg = C.lighter })
hl("@string.special.url", { fg = C.primary, underline = true })
hl("@character", { fg = C.lighter })
hl("@character.special", { fg = C.lighter })
hl("@number", { fg = C.lighter })
hl("@number.float", { fg = C.lighter })
hl("@boolean", { fg = C.muted })
hl("@float", { fg = C.lighter })
hl("@function", { fg = C.primary })
hl("@function.builtin", { fg = C.primary })
hl("@function.call", { fg = C.primary })
hl("@function.macro", { fg = C.muted })
hl("@function.method", { fg = C.primary })
hl("@function.method.call", { fg = C.primary })
hl("@constructor", { fg = C.lighter })
hl("@parameter", { fg = C.fg0 })
hl("@variable", { fg = C.fg0 })
hl("@variable.builtin", { fg = C.primary })
hl("@variable.member", { fg = C.fg0 })
hl("@variable.parameter", { fg = C.fg0 })
hl("@constant", { fg = C.lighter })
hl("@constant.builtin", { fg = C.primary })
hl("@constant.macro", { fg = C.lighter })
hl("@module", { fg = C.muted })
hl("@module.builtin", { fg = C.muted })
hl("@label", { fg = C.muted })
hl("@operator", { fg = C.primary })
hl("@keyword", { fg = C.dark })
hl("@keyword.conditional", { fg = C.dark })
hl("@keyword.repeat", { fg = C.dark })
hl("@keyword.return", { fg = C.dark })
hl("@keyword.debug", { fg = C.lighter })
hl("@keyword.exception", { fg = C.darker })
hl("@keyword.function", { fg = C.dark })
hl("@keyword.import", { fg = C.muted })
hl("@keyword.operator", { fg = C.primary })
hl("@keyword.storage", { fg = C.dark })
hl("@keyword.type", { fg = C.muted })
hl("@keyword.type.qualifier", { fg = C.muted })
hl("@keyword.modifier", { fg = C.dark })
hl("@type", { fg = C.muted })
hl("@type.builtin", { fg = C.muted })
hl("@type.definition", { fg = C.muted })
hl("@type.qualifier", { fg = C.muted })
hl("@storageclass", { fg = C.dark })
hl("@attribute", { fg = C.lighter })
hl("@attribute.builtin", { fg = C.lighter })
hl("@property", { fg = C.fg0 })
hl("@field", { fg = C.fg0 })
hl("@namespace", { fg = C.muted })
hl("@include", { fg = C.muted })
hl("@preproc", { fg = C.muted })
hl("@define", { fg = C.lighter })
hl("@macro", { fg = C.lighter })
hl("@tag", { fg = C.dark })
hl("@tag.attribute", { fg = C.lighter })
hl("@tag.delimiter", { fg = C.fg1 })
hl("@method", { fg = C.primary })
hl("@method.call", { fg = C.primary })
hl("@exception", { fg = C.darker })
hl("@debug", { fg = C.lighter })
hl("@text", { fg = C.fg0 })
hl("@text.strong", { bold = true })
hl("@text.emphasis", { italic = true })
hl("@text.underline", { underline = true })
hl("@text.strike", { strikethrough = true })
hl("@text.title", { fg = C.primary, bold = true })
hl("@text.literal", { fg = C.light })
hl("@text.uri", { fg = C.primary, underline = true })
hl("@text.quote", { fg = C.fg1, italic = true })
hl("@text.math", { fg = C.lighter })
hl("@text.environment", { fg = C.muted })
hl("@text.environment.name", { fg = C.lighter })
hl("@text.note", { fg = C.primary })
hl("@text.warning", { fg = C.lighter })
hl("@text.danger", { fg = C.darker })
hl("@text.reference", { fg = C.muted })
hl("@text.todo", { fg = C.lighter })
hl("@markup.heading", { fg = C.primary, bold = true })
hl("@markup.heading.1", { fg = C.primary, bold = true })
hl("@markup.heading.2", { fg = C.dark, bold = true })
hl("@markup.heading.3", { fg = C.lighter, bold = true })
hl("@markup.heading.4", { fg = C.light, bold = true })
hl("@markup.heading.5", { fg = C.muted, bold = true })
hl("@markup.heading.6", { fg = C.darker, bold = true })
hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.strikethrough", { strikethrough = true })
hl("@markup.underline", { underline = true })
hl("@markup.link", { fg = C.primary, underline = true })
hl("@markup.link.label", { fg = C.primary })
hl("@markup.link.url", { fg = C.primary, underline = true })
hl("@markup.list", { fg = C.fg1 })
hl("@markup.list.checked", { fg = C.light })
hl("@markup.list.unchecked", { fg = C.fg1 })
hl("@markup.raw", { fg = C.light })
hl("@markup.quote", { fg = C.fg1, italic = true })
hl("@markup.math", { fg = C.lighter })
hl("@markup.environment", { fg = C.muted })

hl("DiagnosticError", { fg = C.darker })
hl("DiagnosticWarn", { fg = C.lighter })
hl("DiagnosticInfo", { fg = C.primary })
hl("DiagnosticHint", { fg = C.muted })
hl("DiagnosticOk", { fg = C.light })
hl("DiagnosticUnderlineError", { undercurl = true, sp = C.darker })
hl("DiagnosticUnderlineWarn", { undercurl = true, sp = C.lighter })
hl("DiagnosticUnderlineInfo", { undercurl = true, sp = C.primary })
hl("DiagnosticUnderlineHint", { undercurl = true, sp = C.muted })
hl("DiagnosticUnderlineOk", { undercurl = true, sp = C.light })
hl("DiagnosticSignError", { fg = C.darker, bg = C.bg0 })
hl("DiagnosticSignWarn", { fg = C.lighter, bg = C.bg0 })
hl("DiagnosticSignInfo", { fg = C.primary, bg = C.bg0 })
hl("DiagnosticSignHint", { fg = C.muted, bg = C.bg0 })
hl("DiagnosticSignOk", { fg = C.light, bg = C.bg0 })
hl("DiagnosticVirtualTextError", { fg = C.darker, bg = C.bg1 })
hl("DiagnosticVirtualTextWarn", { fg = C.lighter, bg = C.bg1 })
hl("DiagnosticVirtualTextInfo", { fg = C.primary, bg = C.bg1 })
hl("DiagnosticVirtualTextHint", { fg = C.muted, bg = C.bg1 })
hl("DiagnosticVirtualTextOk", { fg = C.light, bg = C.bg1 })
hl("DiagnosticFloatingError", { fg = C.darker, bg = C.bg1 })
hl("DiagnosticFloatingWarn", { fg = C.lighter, bg = C.bg1 })
hl("DiagnosticFloatingInfo", { fg = C.primary, bg = C.bg1 })
hl("DiagnosticFloatingHint", { fg = C.muted, bg = C.bg1 })
hl("DiagnosticFloatingOk", { fg = C.light, bg = C.bg1 })
hl("LspReferenceText", { bg = C.bg2 })
hl("LspReferenceRead", { bg = C.bg2, fg = C.primary })
hl("LspReferenceWrite", { bg = C.bg2, fg = C.lighter })
hl("LspCodeLens", { fg = C.fg1 })
hl("LspCodeLensSeparator", { fg = C.border })
hl("LspSignatureActiveParameter", { fg = C.dark, bold = true })
hl("LspInlayHint", { fg = C.fg1, bg = C.bg1 })
hl("DiagnosticUnnecessary", { fg = C.fg1, italic = true })
hl("DiagnosticDeprecated", { fg = C.fg1, strikethrough = true })

local legacy_links = {
  LspDiagnosticsDefaultError = "DiagnosticError",
  LspDiagnosticsDefaultWarning = "DiagnosticWarn",
  LspDiagnosticsDefaultInformation = "DiagnosticInfo",
  LspDiagnosticsDefaultHint = "DiagnosticHint",
  LspDiagnosticsSignError = "DiagnosticSignError",
  LspDiagnosticsSignWarning = "DiagnosticSignWarn",
  LspDiagnosticsSignInformation = "DiagnosticSignInfo",
  LspDiagnosticsSignHint = "DiagnosticSignHint",
  LspDiagnosticsUnderlineError = "DiagnosticUnderlineError",
  LspDiagnosticsUnderlineWarning = "DiagnosticUnderlineWarn",
  LspDiagnosticsUnderlineInformation = "DiagnosticUnderlineInfo",
  LspDiagnosticsUnderlineHint = "DiagnosticUnderlineHint",
  LspDiagnosticsVirtualTextError = "DiagnosticVirtualTextError",
  LspDiagnosticsVirtualTextWarning = "DiagnosticVirtualTextWarn",
  LspDiagnosticsVirtualTextInformation = "DiagnosticVirtualTextInfo",
  LspDiagnosticsVirtualTextHint = "DiagnosticVirtualTextHint",
}
for group, target in pairs(legacy_links) do
  vim.api.nvim_set_hl(0, group, { link = target, default = true })
end

-- Extra treesitter groups
hl("@keyword.directive", { fg = C.muted })
hl("@comment.documentation", { fg = C.light, italic = true })
hl("@string.special.path", { fg = C.lighter })
hl("@text.diff.add", { fg = C.light })
hl("@text.diff.delete", { fg = C.darker })
hl("@diff.plus", { fg = C.light })
hl("@diff.minus", { fg = C.darker })
hl("@diff.delta", { fg = C.lighter })
hl("@diff.none", { fg = C.fg1 })

-- GitSigns
hl("GitSignsAdd", { fg = C.light, bg = C.bg0 })
hl("GitSignsChange", { fg = C.lighter, bg = C.bg0 })
hl("GitSignsDelete", { fg = C.darker, bg = C.bg0 })
hl("GitSignsAddLn", { fg = C.light, bg = C.bg0 })
hl("GitSignsChangeLn", { fg = C.lighter, bg = C.bg0 })
hl("GitSignsDeleteLn", { fg = C.darker, bg = C.bg0 })

-- blink.cmp
hl("BlinkCmpMenu", { fg = C.fg0, bg = C.bg1 })
hl("BlinkCmpMenuSelection", { fg = C.bg0, bg = C.primary })
hl("BlinkCmpMenuBorder", { fg = C.dark, bg = C.bg1 })
hl("BlinkCmpScrollBarThumb", { bg = C.border })
hl("BlinkCmpScrollBarTrack", { bg = C.bg2 })
local cmp_kinds = {
  Text = C.fg1, Method = C.primary, Function = C.primary, Constructor = C.lighter,
  Field = C.fg0, Variable = C.fg0, Class = C.lighter, Interface = C.muted,
  Module = C.muted, Property = C.fg0, Unit = C.fg1, Value = C.lighter,
  Enum = C.lighter, Keyword = C.dark, Snippet = C.light, Color = C.fg1,
  File = C.fg1, Reference = C.fg1, Folder = C.fg1, EnumMember = C.lighter,
  Constant = C.lighter, Struct = C.lighter, Event = C.lighter, Operator = C.primary,
  TypeParameter = C.muted,
}
for kind, color in pairs(cmp_kinds) do
  hl("BlinkCmpKind" .. kind, { fg = color })
end

-- Trouble
hl("TroubleText", { fg = C.fg0 })
hl("TroubleCount", { fg = C.bg0, bg = C.darker })
hl("TroubleIndent", { fg = C.border })
hl("TroubleSignError", { fg = C.darker })
hl("TroubleSignWarn", { fg = C.lighter })
hl("TroubleSignInfo", { fg = C.primary })
hl("TroubleSignHint", { fg = C.muted })
hl("TroubleSignOk", { fg = C.light })

-- Flash
hl("FlashLabel", { fg = C.bg0, bg = C.dark, bold = true })
hl("FlashMatch", { fg = C.dark, bold = true })
hl("FlashCurrent", { fg = C.bg0, bg = C.lighter, bold = true })

-- Oil
hl("OilDir", { fg = C.primary })
hl("OilDirIcon", { fg = C.primary })
hl("OilHidden", { fg = C.fg1 })
hl("OilLink", { fg = C.primary, underline = true })
hl("OilFile", { fg = C.fg0 })
hl("OilCopy", { fg = C.light })
hl("OilMove", { fg = C.lighter })
hl("OilTermCursor", { fg = C.bg0, bg = C.dark })

hl("CmpItemAbbr", { fg = C.fg0 })
hl("CmpItemAbbrMatch", { fg = C.primary })
hl("CmpItemAbbrMatchFuzzy", { fg = C.primary })
hl("CmpItemMenu", { fg = C.fg1 })
hl("CmpItemKindKeyword", { fg = C.dark })
hl("CmpItemKindFunction", { fg = C.primary })
hl("CmpItemKindMethod", { fg = C.primary })
hl("CmpItemKindVariable", { fg = C.fg0 })
hl("CmpItemKindField", { fg = C.fg0 })
hl("CmpItemKindProperty", { fg = C.fg0 })
hl("CmpItemKindClass", { fg = C.lighter })
hl("CmpItemKindStruct", { fg = C.lighter })
hl("CmpItemKindInterface", { fg = C.muted })
hl("CmpItemKindModule", { fg = C.muted })
hl("CmpItemKindValue", { fg = C.lighter })
hl("CmpItemKindEnum", { fg = C.lighter })
hl("CmpItemKindEnumMember", { fg = C.lighter })
hl("CmpItemKindConstant", { fg = C.lighter })
hl("CmpItemKindUnit", { fg = C.fg1 })
hl("CmpItemKindSnippet", { fg = C.light })
hl("CmpItemKindFile", { fg = C.fg1 })
hl("CmpItemKindFolder", { fg = C.fg1 })
hl("CmpItemKindColor", { fg = C.fg1 })
hl("CmpItemKindReference", { fg = C.fg1 })
hl("CmpItemKindText", { fg = C.fg1 })
hl("CmpItemKindTypeParameter", { fg = C.muted })
hl("CmpItemKindOperator", { fg = C.primary })

local term_colors = {
  "#0A0A12", "#555555", "#E0E0E0", "#CCCCCC",
  "#CCCCCC", "#888888", "#E0E0E0", "#E8E6F0",
  "#1C1C28", "#666666", "#DDDDDD", "#AAAAAA",
  "#AAAAAA", "#999999", "#EEEEEE", "#EBEBF2",
}
for i, color in ipairs(term_colors) do
  vim.g["terminal_color_" .. i - 1] = color
end
