[color]
  ui = auto
  diff = auto
  status = auto
  branch = auto
  interactive = auto

[delta]
  navigate = true
  line-numbers = true
  hyperlinks = true
  side-by-side = false
  syntax-theme = Monokai Extended

[delta "decorations"]
  commit-decoration-style = bold yellow box ul
  commit-style = raw
  file-style = omit
  hunk-header-decoration-style = yellow box
  hunk-header-style = file line-number syntax

[interactive]
  diffFilter = delta --color-only

[grep]
  lineNumber = true
  patternType = perl
