---
- name: Setup Local Development Environment
  hosts: localhost
  become: true
  gather_facts: true

  vars:
    user_home: "{{ ansible_env.HOME }}"
    dotfiles_dir: "{{ user_home }}/.dotfiles"

  tasks:
    - name: Include Debian-specific tasks
      ansible.builtin.include_tasks: tasks/debian.yml
      when: ansible_facts.os_family == "Debian"
      tags:
        - system
        - update
        - essentials

    - name: Include Arch-specific tasks
      ansible.builtin.include_tasks: tasks/arch.yml
      when: ansible_facts.os_family == "Archlinux"
      tags:
        - system
        - update
        - essentials

    - name: Include zoxide installation
      ansible.builtin.include_tasks: tasks/zoxide.yml

    - name: Include Zsh and Oh My Zsh setup
      ansible.builtin.include_tasks: tasks/zsh.yml

    - name: Include Neovim installation tasks
      ansible.builtin.include_tasks: tasks/neovim.yml
