[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.90
padding.x = 8
padding.y = 8

[colors.primary]
background = "#191724"
foreground = "#e0def4"

[colors.normal]
black   = "#21202e"
red     = "#eb6f92"
green   = "#31748f"
yellow  = "#f6c177"
blue    = "#9ccfd8"
magenta = "#c4a7e7"
cyan    = "#ebbcba"
white   = "#e0def4"

[colors.bright]
black   = "#403d52"
red     = "#eb6f92"
green   = "#31748f"
yellow  = "#f6c177"
blue    = "#9ccfd8"
magenta = "#c4a7e7"
cyan    = "#ebbcba"
white   = "#e0def4"

[colors.cursor]
cursor = "#c4a7e7"
text = "#191724"

[colors.selection]
background = "#403d52"
text = "#e0def4"

